;; Keys
(global-set-key `[f6] `toggle-truncate-lines)
(global-set-key `[f8] `call-last-kbd-macro)
(global-set-key [?\C-}] `next-multiframe-window)
(global-set-key [?\C-{] `previous-multiframe-window)
(global-set-key `[C-f5] `revert-buffer-unconditionally)
(global-set-key (kbd "S-C-<left>") 'shrink-window-horizontally)
(global-set-key (kbd "S-C-<right>") 'enlarge-window-horizontally)
(global-set-key (kbd "S-C-<down>") 'shrink-window)
(global-set-key (kbd "S-C-<up>") 'enlarge-window)
(global-set-key "\M-g" 'goto-line)
(global-set-key '[f7] '(lambda () (interactive) (switch-to-buffer nil)))
(global-set-key (kbd "C-c C-u") 'comment-or-uncomment-region)
(global-set-key (kbd "C-c d") 'dedicated-mode)
(global-set-key (kbd "M-<down>") 'scroll-down-line)
(global-set-key (kbd "M-<up>") 'scroll-up-line)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)
(global-set-key (kbd "C-c C-g") 'magit-status)
